
#=====================================
#    Electromagnetic  processes
#=====================================

#=============
# For Leptons
#=============

/gate/physics/addProcess PhotoElectric
/gate/physics/processes/PhotoElectric/setModel StandardModel

/gate/physics/addProcess Compton
/gate/physics/processes/Compton/setModel StandardModel

/gate/physics/addProcess GammaConversion
/gate/physics/processes/GammaConversion/setModel StandardModel

/gate/physics/addProcess ElectronIonisation
/gate/physics/processes/ElectronIonisation/setModel StandardModel e-
/gate/physics/processes/ElectronIonisation/setModel StandardModel e+
/gate/physics/processes/ElectronIonisation/setStepFunction e+ 0.02 0.1 mm		# 0.2 0.1 in origine
/gate/physics/processes/ElectronIonisation/setStepFunction e- 0.02 0.1 mm
/gate/physics/processes/ElectronIonisation/setLinearLossLimit electron 0.01		# 0.01 in origine

/gate/physics/addProcess Bremsstrahlung
/gate/physics/processes/Bremsstrahlung/setModel StandardModel e-
/gate/physics/processes/Bremsstrahlung/setModel StandardModel e+

/gate/physics/addProcess PositronAnnihilation

/gate/physics/addProcess eMultipleScattering e-
/gate/physics/addProcess eMultipleScattering e+

#/gate/physics/addProcess SingleScattering e-
#/gate/physics/addProcess SingleScattering e+

/gate/physics/processes/eMultipleScattering/setGeometricalStepLimiterType e- distanceToBoundary
/gate/physics/processes/eMultipleScattering/setGeometricalStepLimiterType e+ distanceToBoundary

#=========
# Options
#=========

/gate/physics/setEMin 0.1 keV
/gate/physics/setEMax 10 GeV
/gate/physics/setDEDXBinning 350
/gate/physics/setLambdaBinning 350

#=====================================
# EM processes for hadrons
#=====================================

/gate/physics/addProcess HadronIonisation 			# si può anche fare: HadronIonisatio proton , e non rimuovere gli altri processi però non so cosa accada ai pioni,il risultato non cambia
/gate/physics/removeProcess HadronIonisation deuteron
/gate/physics/removeProcess HadronIonisation triton
/gate/physics/removeProcess HadronIonisation He3
/gate/physics/removeProcess HadronIonisation alpha
/gate/physics/removeProcess HadronIonisation GenericIon
/gate/physics/processes/HadronIonisation/setStepFunction proton 0.02 0.05 mm    # 0.2 0.05 in origine
/gate/physics/processes/HadronIonisation/setStepFunction pi+    0.02 0.05 mm
/gate/physics/processes/HadronIonisation/setStepFunction pi-    0.02 0.05 mm
/gate/physics/processes/HadronIonisation/setLinearLossLimit proton 0.01		# 0.01 in origine

/gate/physics/addProcess IonIonisation 
/gate/physics/processes/IonIonisation/setStepFunction GenericIon 0.01 0.02 mm   # 0.1 0.02 in origine
/gate/physics/processes/IonIonisation/setStepFunction alpha      0.01 0.02 mm
/gate/physics/processes/IonIonisation/setStepFunction deuteron   0.01 0.02 mm
/gate/physics/processes/IonIonisation/setStepFunction triton     0.01 0.02 mm
/gate/physics/processes/IonIonisation/setStepFunction He3        0.01 0.02 mm

        /gate/physics/addProcess hMultipleScattering proton
#	/gate/physics/addProcess SingleScattering proton
	/gate/physics/addProcess hMultipleScattering alpha
	/gate/physics/addProcess hMultipleScattering deuteron
	/gate/physics/addProcess hMultipleScattering triton
	/gate/physics/addProcess hMultipleScattering He3
	/gate/physics/addProcess hMultipleScattering GenericIon


#/gate/physics/addProcess hMultipleScattering 

/gate/physics/processes/eMultipleScattering/setGeometricalStepLimiterType proton safety
/gate/physics/processes/hMultipleScattering/setGeometricalStepLimiterType deuteron distanceToBoundary
/gate/physics/processes/hMultipleScattering/setGeometricalStepLimiterType triton distanceToBoundary
/gate/physics/processes/hMultipleScattering/setGeometricalStepLimiterType He3 distanceToBoundary
/gate/physics/processes/hMultipleScattering/setGeometricalStepLimiterType alpha distanceToBoundary
/gate/physics/processes/hMultipleScattering/setGeometricalStepLimiterType GenericIon distanceToBoundary

#=====================================
# Hadronic  processes for hadrons
#=====================================

/gate/physics/addProcess HadronElastic GenericIon
/gate/physics/processes/HadronElastic/setModel G4LElastic GenericIon

/gate/physics/addProcess HadronElastic
/gate/physics/processes/HadronElastic/setModel G4HadronElastic
/gate/physics/processes/HadronElastic/setDataSet G4HadronElasticDataSet

/gate/physics/addProcess ProtonInelastic
/gate/physics/processes/ProtonInelastic/setModel G4BinaryCascade
/gate/physics/processes/ProtonInelastic/G4BinaryCascade/setEmin 170 MeV
/gate/physics/processes/ProtonInelastic/G4BinaryCascade/setEmax 500 GeV
/gate/physics/processes/ProtonInelastic/setModel PreCompound
/gate/physics/processes/ProtonInelastic/PreCompound/setEmin 0 MeV
/gate/physics/processes/ProtonInelastic/PreCompound/setEmax 170 MeV
/gate/physics/processes/ProtonInelastic/setDataSet G4ProtonInelasticCrossSection   # aggiunto da me
#/gate/physics/addProcess ProtonInelastic
#/gate/physics/processes/ProtonInelastic/setModel PreCompound			   # aggiunto ottimizzazione Loic, ho utilizzato l'altro in quanto proveniente da una physicslist + aggiornata
#/gate/physics/processes/ProtonInelastic/setDataSet G4ProtonInelasticCrossSection



/gate/physics/addProcess IonInelastic
/gate/physics/processes/IonInelastic/setModel G4BinaryLightIonReaction
/gate/physics/processes/IonInelastic/setModel G4LEDeuteronInelastic deuteron
/gate/physics/processes/IonInelastic/setModel G4LETritonInelastic triton
/gate/physics/processes/IonInelastic/setModel G4LEAlphaInelastic alpha
/gate/physics/processes/IonInelastic/G4BinaryLightIonReaction/setEmin 80 MeV deuteron
/gate/physics/processes/IonInelastic/G4BinaryLightIonReaction/setEmax 20 GeV deuteron
/gate/physics/processes/IonInelastic/G4BinaryLightIonReaction/setEmin 80 MeV triton
/gate/physics/processes/IonInelastic/G4BinaryLightIonReaction/setEmax 20 GeV triton
/gate/physics/processes/IonInelastic/G4BinaryLightIonReaction/setEmin 80 MeV alpha
/gate/physics/processes/IonInelastic/G4BinaryLightIonReaction/setEmax 20 GeV alpha
/gate/physics/processes/IonInelastic/G4LEDeuteronInelastic/setEmin 0 MeV deuteron
/gate/physics/processes/IonInelastic/G4LEDeuteronInelastic/setEmax 80 MeV deuteron        # 80 MeV
/gate/physics/processes/IonInelastic/G4LETritonInelastic/setEmin 0 MeV triton
/gate/physics/processes/IonInelastic/G4LETritonInelastic/setEmax 80 MeV triton		 # 80 MeV
/gate/physics/processes/IonInelastic/G4LEAlphaInelastic/setEmin 0 MeV alpha
/gate/physics/processes/IonInelastic/G4LEAlphaInelastic/setEmax 80 MeV alpha		 # 80 MeV
/gate/physics/processes/IonInelastic/setDataSet G4IonsShenCrossSection GenericIon
/gate/physics/processes/IonInelastic/setDataSet G4TripathiLightCrossSection deuteron
/gate/physics/processes/IonInelastic/setDataSet G4TripathiLightCrossSection triton
/gate/physics/processes/IonInelastic/setDataSet G4TripathiLightCrossSection alpha

/gate/physics/addProcess PionPlusInelastic
/gate/physics/processes/PionPlusInelastic/setModel G4LEPionPlusInelastic

/gate/physics/addProcess PionMinusInelastic
/gate/physics/processes/PionMinusInelastic/setModel G4LEPionMinusInelastic

#/gate/physics/addProcess NeutronCapture
#/gate/physics/processes/NeutronCapture/setModel G4LCapture	
/gate/physics/addProcess NeutronCapture
/gate/physics/processes/NeutronCapture/setModel G4LCapture
/gate/physics/processes/NeutronCapture/setModel G4NeutronHPorLCapture
/gate/physics/processes/NeutronCapture/G4NeutronHPorLCapture/setEmax 20 MeV neutron
/gate/physics/processes/NeutronCapture/G4LCapture/setEmin 19.9 MeV neutron
/gate/physics/processes/NeutronCapture/setDataSet G4HadronCaptureDataSet
/gate/physics/processes/NeutronCapture/setDataSet G4NeutronHPCaptureData

#/gate/physics/addProcess Fission
#/gate/physics/processes/Fission/setModel G4LFission
/gate/physics/addProcess Fission
/gate/physics/processes/Fission/setModel G4LFission
/gate/physics/processes/Fission/setModel G4NeutronHPorLFission
/gate/physics/processes/Fission/G4NeutronHPorLFission/setEmax 20 MeV neutron
/gate/physics/processes/Fission/G4LFission/setEmin 19.9 MeV neutron
/gate/physics/processes/Fission/setDataSet G4HadronFissionDataSet
/gate/physics/processes/Fission/setDataSet G4NeutronHPFissionData

#/gate/physics/addProcess NeutronInelastic                                                
#/gate/physics/processes/NeutronInelastic/setModel PreCompound                            
/gate/physics/addProcess NeutronInelastic
/gate/physics/processes/NeutronInelastic/setModel PreCompound
/gate/physics/processes/NeutronInelastic/setModel G4NeutronHPInelastic
/gate/physics/processes/NeutronInelastic/G4NeutronHPInelastic/setEmax 20 MeV neutron
/gate/physics/processes/NeutronInelastic/PreCompound/setEmin 19.9 MeV neutron
/gate/physics/processes/NeutronInelastic/setDataSet G4NeutronInelasticCrossSection   # aggiornata, prima era G4HadronInelasticDataSet
/gate/physics/processes/NeutronInelastic/setDataSet G4HadronInelasticDataSet         # G4NeutronHPInelasticData dava degli errori, ho messo quella più generale per gli adroni che ha validità per qualsiasi 											     # range di energia e vale per i neutroni. Si perdono forse degli effetti ad alta precisione che l'altro dataset forniva

/gate/physics/addProcess Decay
/gate/physics/addProcess RadioactiveDecay   	# aggiunto

